Add Right Margin Guideline
leo-editor/leo-editor pull request #2621
Opened 2022-04-24 13:18 UTC by tbpassin

Add optional right margin guideline in body. A new help menu item is also added to explain the settings.  Tested with both pyqt5 and pyqt6.

test-all:
```
Ran 923 tests in 20.029s
OK (skipped=8)
```

pylint: 9.94/10

2022-04-24 19:44 UTC, edreamleo requested changes
Please create the help menu entries by adding entries to leoSettings.leo. See:

leoSettings.leo#@settings-->Menus-->@menus-->@menu &Help-->@menu &Open Help topics

2022-04-25 01:13 UTC, tbpassin commented
OK, I'll get at that.

2022-04-25 01:39 UTC, tbpassin commented
Done - help menu items now defined in leoSettings.leo.

2022-04-26 11:15 UTC, edreamleo reviewed
The code looks good. Not sure about whether the help text is in the right place, but that's a nit that we can handle after the merge.

I won't approve the PR yet, because it should be merged into devel after releasing 6.6.1. I'll approve when that happens.

2022-04-28 12:24 UTC, tbpassin commented
"All completed 6.6.2 work has been merged into devel".  Not quite : )

2022-04-28 14:11 UTC, merged

2022-04-28 14:15 UTC, edreamleo commented
@tbpassin Thanks for the reminder. I have just merged this PR.

2022-04-28 14:33 UTC, tbpassin commented
Thanks, Edward!