Fixes #3074, exception on startup with --theme= for some themes.
leo-editor/leo-editor pull request #3082
Opened 2023-01-21 03:39 UTC by tbpassin

Fixes #3074.

2023-01-21 10:08 UTC, edreamleo requested changes
Please delete the backslash-newline and simplify the code.

Something like this (not tested):
```python
            if (w == getattr(c.frame.body, 'widget', None)
                and c.config.getBool('show-rmargin-guide')
            ):
```

2023-01-21 13:54 UTC, tbpassin commented
I think that the check for ` w == c.frame.body.widget` needs to be there in some form, because this class, _LeoQTextBrowser_, is also used in other places that are not the frame's body widget.  We don't want to try to paint a right hand margin in those cases (or maybe some of them would like it, but not all).

I'll see if the expression can be made more graceful.

2023-01-21 14:21 UTC, tbpassin commented
OK, I made the requested change and also took care of most pylint suggestions.

2023-01-22 07:56 UTC, edreamleo approved these changes

2023-01-22 07:56 UTC, merged