PR for #3121: headline numbers
leo-editor/leo-editor pull request #3227
Opened 2023-03-28 07:13 UTC by edreamleo

See #3121.

PR #3228 (merged into devel) adds related undo/redo helpers.

- [x] Add `hn-add-all`, `hn-add-subtree`, `hn-delete-all`, and `hn-delete-subtree` commands,
    including various aliases.
    - Redraw the resulting trees and mark nodes dirty.
    - Add docstrings.
- [x] Make all commands undoable.

2023-03-28 11:40 UTC, tbpassin requested changes
1. Line 1089: def hn_add()
    Supply a docstring explaining what this method is intended to do.
    Given a good docstring here, the other related commands probably
    do not need docstrings.  Without a docstring, the purpose of this
    command is obscure.

2. Line 1119: hn_pattern = re.compile(r'^[0-9]+(\.[0-9]+)* ')
    Move this line to the top of the node.

2023-03-28 12:05 UTC, edreamleo commented
@tbpassin I'll add docstrings.

2023-03-29 10:37 UTC, edreamleo commented
@tbpassin I've made all your requested changes. Please review again :-)

2023-03-29 12:20 UTC, edreamleo commented
@tbpassin
- Named sections are always within an `@<file>` tree, so there is no longer any need to mention such nodes separately.
- The function appears inside the node because it is used nowhere else.

2023-03-29 13:46 UTC, edreamleo commented
@tbpassin `@<file>` means any kind of external file.

2023-03-29 20:00 UTC, merged