PR for #3231: append to sys.path
leo-editor/leo-editor pull request #3233
Opened 2023-04-01 11:26 UTC by edreamleo

See #3231.

**Important**: Changing

2023-04-01 12:40 UTC, tbpassin requested changes
leoflexx.py lines 46ff:
    
    # This is what Leo typically does.
    # pylint: disable=wrong-import-position
    path = os.getcwd()
    if path not in sys.path:
        sys.path.append(path)
    g.appendToSysPath(os.getcwd())

    # JS code can *not* use g.trace, g.callers or g.pdb.
    from leo.core import leoGlobals as g
    
Uses g before importing it.

2023-04-01 12:41 UTC, tbpassin commented
This why I didn't want to dive in and "fix" this issue myself.  I wouldn't have known where it should and shouldn't be used.

2023-04-02 10:49 UTC, edreamleo commented
@tbpassin Thanks for your review. Rev b7b0f14 fixes the problem you found.

Your caution concerning this issue was well founded. My first thought was to remove the weird special case for Windows in `g.os_path_finalize`. But after removing that code Leo couldn't find any of the `@file` nodes in my outline! I'm not sure why that happens but that doesn't matter&mdash;removing the code would be exceptionally dangerous.

So I had no choice but to find all the places where Leo updates `sys.path`.

2023-04-02 12:02 UTC, edreamleo commented
@tbpassin Please review the latest code.

The code no longer uses `g.appendToSysPath function`. It was a faux helper.

2023-04-02 13:30 UTC, tbpassin requested changes
I missed seeing problems about this path because my launching script puts _git/leo-editor_ first on the path.

Don't we want to put the **parent** of the leo directory on the path rather than the leo directory itself?  My programs, and Leo's code base, are littered with imports like `from leo.core import leoNodes`.  That is:
```
import os.path
dir = os.path.normpath(os.path.join(g.app.loadDir, '..'))
g.es(dir)  # C:\Tom\git\leo-editor\leo
```
This isn't the parent of the leo directory.

What is really needed is for `g.app.leoDir\..` to be on the path, isn't it?

```
import os.path
dir = os.path.normpath(os.path.join(g.app.leoDir, '..'))
g.es(dir)  # C:\Tom\git\leo-editor

```

2023-04-02 13:49 UTC, edreamleo commented
@tbpassin Thanks for your comment.  I think you are correct, but I think you meant to say:

What is really needed is for g.app.leoDir\.. to be on the path, isn't it?

```python
dir = os.path.normpath(os.path.join(g.app.leoDir, '..', '..'))   # Go back an extra level.
g.es(dir)  # C:\Tom\git\leo-editor
```
Right?

2023-04-02 14:15 UTC, tbpassin commented
No, it's correct the way I wrote it.  You might be mixing up `g.app.leoDir` and `g.app.loadDir`:

```
g.es('g.app.leoDir:', g.app.leoDir)
g.es('g.app.loadDir:', g.app.loadDir)
# Displays:
g.app.leoDir: C:/Tom/git/leo-editor/leo
g.app.loadDir: C:/Tom/git/leo-editor/leo/core
```

2023-04-02 14:27 UTC, edreamleo commented
@tbpassin I see. Please review the latest code. I think it's equivalent to your suggestions.

2023-04-02 14:28 UTC, edreamleo commented
@tbpassin Also, please have a look at #3235. I'd appreciate your comments.

2023-04-02 14:52 UTC, tbpassin requested changes
`sys.path.append(path)` - I still think this should be `sys.path.insert(0, path)`.  Otherwise some other Leo install might be found first.

2023-04-02 16:08 UTC, edreamleo commented
@tbpassin I agree. The pattern should use `sys.path.insert(0, path)`.

2023-04-02 16:15 UTC, edreamleo commented
@tbpassin I think I've complied with all your requests. Please approve this PR if so.

2023-04-02 17:04 UTC, tbpassin requested changes
1. _runLeo.py_, line 37:

```
if path not in sys.path:
    # print('appending %s to sys.path' % path)
    sys.path.append(path)
```
Shouldn't this use `insert(0, path)` instead?

2. _checkerCommands_, line 608, comment:
`# Make sure the leo-editor directory is on sys.path.`
A nit, but a PyPi install won't have _leo-editor_ - how about "the parent directory of leo" instead?

Almost there!

2023-04-03 03:16 UTC, merged