PR for #3416: quirp in refresh-from-disk
leo-editor/leo-editor pull request #3433
Opened 2023-07-09 08:44 UTC by edreamleo

See #3416.

2023-07-09 13:21 UTC, tbpassin requested changes
I would like there to be no more changes to signatures of long-established methods and functions.  You have no idea who else is using these calls.  One of Leo's principles has been that any part of the leo code can be called by any plugin or script. This means that it's all part of the API.  If there were a published API that included only a subset of Leo's calls, then it would be fine to change ones not in that subset.  But that's not the case.

In this PR it would have been simple to create a new method with a new name and call signature.  It's not too late to do this.

Summary: I won't approve this PR as is because it changes the API.

2023-07-09 14:23 UTC, edreamleo commented
@tbpassin I basically only care whether *you* use `at.readOneAtEditNode` and `at.readOneAtAsisNode` :-)

I understand your complaint, but I don't think it's worth delaying the change.  Rev 103f5c5 of the `6.7.4` documents the change.

Also, Félix should remove the `fn` positional arg in leoJS.

2023-07-09 18:00 UTC, boltex approved these changes
This is a small break in the API because of the signature change, and should be documented as such in the **'breaking changes'** section of the **release notes/readme** (as is the case when such things happen. )

2023-07-10 00:35 UTC, edreamleo commented
@tbpassin I'll be sure to document the change in the 6.7.4 branch.

2023-07-10 00:35 UTC, merged

2023-07-10 02:15 UTC, tbpassin reviewed
I didn't really find anything to remark on, except for the signature change.

2023-07-10 09:16 UTC, edreamleo commented
@tbpassin The release notes now prominently mention the changes to Leo's API.