PR for #3734: Suppress git-diff errors
leo-editor/leo-editor pull request #3735
Opened 2023-12-27 17:23 UTC by edreamleo

See #3734.

2023-12-27 17:50 UTC, tbpassin requested changes
This needs a bit more thought.
```
        try:
            with open(path, 'rb') as f:
                b = f.read()
            return g.toUnicode(b).replace('\r', '')
        except Exception:
            g.es_print('Can not read', path)
            g.es_exception()
            # This is not an error. The user has inserted or deleted the file.
```
1. Check the file existence first before trying to read it.  There is no reason to try to save a line or two of code by asking the except clause to do it, because:
2. There might be other exception reasons and this code cannot tell them apart. 
3. Better not to use the ancestral _Exception_ class.

2023-12-27 18:06 UTC, edreamleo commented
@tbpassin Good idea. I'll do as you suggest.

2023-12-27 18:20 UTC, edreamleo commented
@tbpassin I've made the change you requested.

2023-12-28 04:16 UTC, tbpassin approved these changes

2023-12-28 04:29 UTC, merged