PR for #3990: uAs on @edit nodes
leo-editor/leo-editor pull request #4005
Opened 2024-07-16 16:32 UTC by edreamleo

See #3990.

- [x] Generalize

2024-07-16 17:22 UTC, tbpassin requested changes
_fileCommands.py_
1. Line 2057 "
 ` v_head = f'<v t="{gnx}"{attrs}>'`

I don't see how this can produce well-formed XML.  The returned values from `fc.putDescendentVnodeUas()` look like this:

`descendentVnodeUnknownAttributes="7d710058010000003071017d7102580200000061317103580e0000007468697320697320612074657374710473732e"`

There is no leading space, so there will be no space after `t="{gnx}". Also, at around line 2087, all attributes are accumulated without spaces between them, by means of `"".join(...)`.

In XML, attributes must be whitespace-separated.

2024-07-16 20:51 UTC, edreamleo commented
Somehow you have misread the code. In a recent test file the `<v>` elements is:

`<v t="ekr.20240716112233.1" descendentVnodeUnknownAttributes="7d0[big snip]"><vh>@edit c:\test\gnx_test.py</vh></v>`

The corresponding outline node contains an attached todo icon, verifying that the bug has been fixed.

There is a space between the gnx and the attribute.  In any event:

- Leo's read code (in the node `fast.readWithElementTree & helpers`) can still read `.leo` files using `xml.etree.ElementTree`.
- This PR does not change Leo's file format in this respect, so any problem would be a separate issue.

2024-07-16 21:15 UTC, tbpassin approved these changes
OK; I still don't see where the space comes from, but the outline wouldn't load if it were not well-formed.  Anyway, good to check and confirm.

2024-07-16 21:46 UTC, edreamleo commented
@tbpassin Yes, it's always good to check :-) Thanks for your approval.

2024-07-16 21:46 UTC, merged

2024-07-17 03:04 UTC, tbpassin commented
Weren't we going to start calling them "User Attributes" instead of "Unknown Attributes"?

2024-07-17 10:41 UTC, edreamleo commented
@tbpassin Whatever *we* call them, the code isn't going to change :-)