'tnodeList' uncommented as attribute to exclude from being unpickeld with resolveUa. Also deleted extraneous nativeVnodeAttributes object duplicate.
leo-editor/leo-editor pull request #4011
Opened 2024-07-18 04:40 UTC by boltex

Fixes #4010

I tested this by re-opening my old files and re-saving them under a different name and comparing the XML and making sure they also opened properly in Leo. 

(I'll fix LeoJS in the same way very soon to also support old Leo files)

I also made sure to run unit tests this time :) they all pass.

2024-07-18 09:40 UTC, tbpassin approved these changes
1. Line 93 - The trailing comment is now incomplete. Either remove it or change to read something like:
`'tnodeList',  # Removed in Leo 4.7, restored in Leo 6.8.1`

2024-07-18 11:11 UTC, edreamleo requested changes
I agree with Thomas: the comment should mention the full history of `tnodeList`.

This is a significant change to Leo's code.

2024-07-18 11:35 UTC, tbpassin commented
Will this change make it impossible to read pre-4.7 outlines?

2024-07-19 00:06 UTC, boltex commented
@tbpassin @edreamleo  🤔  Hmm,... I suspected that this comment **"# Removed in Leo 4.7"** was marking the deprecation of the tnodelist attribute itself in the leo file format, and not the point where the 'tnodelist' entry in nativeVnodeAttributes was commented out.

So I verified the line's history in the past commits. And indeed, this comment was not made when that line was commented out, it was about marking when the 'tnodelist' became historically retired and irrelevant to the read algorithm. 

So the comment should stand as-is. 

@tbpassin you asked:  **"Will this change make it impossible to read pre-4.7 outlines?"**  This changes nothing in that regard: the tnodelist attribute would be totally ignored regardless.

Note: the tnodelist attribute was plain text list of gnx, not a pickled data string meant to be a UA at all.

As explained here https://github.com/leo-editor/leo-editor/issues/4010 I just make it explicit and obvious with this modification instead of relying on the un-pickle process to error out and trigger the 'catch' of this exception and produce an 'empty string' lingering ghost of a UA which would have haunted the outline forever. :)

2024-07-19 01:15 UTC, edreamleo approved these changes

2024-07-19 01:15 UTC, edreamleo commented
@boltex Thanks for your comments.

2024-07-19 01:15 UTC, merged