PR for #4123: Fix all expand/contract-*-pane commands
leo-editor/leo-editor pull request #4136
Opened 2024-10-27 18:12 UTC by edreamleo

See #4123.

- [x] Delegate expand/contract commands to the `LayoutCacheWidget` class.

2024-10-27 19:59 UTC, tbpassin reviewed
I think that all the contract-* and expand-* can be done with one method of `LayoutCacheWidget`:

```
def change_pane_size(self, widget: str, expand: Bool) -> None:
    # No error checking or guards
    instance = self.get_widget(widget)
    splitter = instance.parent()
    index = splitter.indexOf(instance)
    factor = self.delta if expand else -self.delta
    self.rebalanceSplitter(splitter, index, factor)  # <=== All the work happens here
```

The various minibuffer commands would look like this:

```
@g.command('expand-outline-pane')
def expandBodyPane(event: LeoKeyEvent) -> None:
    """Contract the body pane. Expand the outline/log splitter."""
    c = event.get('c')
    if c is None:
        return
    cache = c.frame.top.layout_cache
    cache.change_pane_size('bodyFrame', True)
```

I'm inclined to think that there should be a separate but similar method of layout_cache for show/hide. We may need to special-case VR3 because it should execute set_freeze() when hidden but I'm not sure if it does - the hide() command is on the splitter and I don't know if it calls the client widget's `hide()` method or not.  A minor point.

2024-10-27 22:38 UTC, tbpassin commented
`Pass widgets, not their names, to expand/contract_pane`

Disagree. Someone has to know how to get the widget, and that is better done by the layout_widget.  Otherwise the minibuffer command has to try to find the right widget, and it will need to use its name to do that.  Just pass the name. It's simpler and easier to understand.

2024-10-27 23:12 UTC, edreamleo commented
@tbpassin It is the `LCW` class, not the minibuffer commands, that knows about widgets. Here is LCW.expand_body:
```python
def expand_body(self):
    """Expand the body pane"""
    self.expand_pane(self.c.frame.body.widget)
```
In other words, we agree about the infrastructure.

Thanks for your remarks about `change_pane_size`. Perhaps there is no need for `LCW.expand/contract_pane_by_name`.

2024-10-27 23:36 UTC, tbpassin commented
I bow to your inside knowledge... I didn't know there was such a thing as c.frame.body.widget,  Is there a c.frame.viewrendered3.widget? Where does c.frame get to know about viewrendered3.widget?

2024-10-28 11:45 UTC, tbpassin commented
> Replace QW by QWidget. LayoutClassWidget is (only!!) a QWidget

It's not a QWidget, it's a class derived from QWidget. I defined the QW bounded type after mypy complained about not recognizing the class. Up until then I thought that mypy would settle for QWidget for derived classes.

2024-10-28 12:25 UTC, edreamleo commented
@tbpassin mypy is happy with my changes. You annotations were unnecessarily complicated and confusing.

2024-10-28 13:03 UTC, tbpassin commented
> @tbpassin mypy is happy with my changes. You annotations were unnecessarily complicated and confusing.

I came up with those annotations and the QW and OD types because mypy wasn't accepting the type annotations I started out with, which included "QWidget" for classes derived from QWidget.

The typing error messages from mypy came when I ran mypy from the minibuffer.  If it gives different results when run externally, that's a problem with the command.  If it gives different results after updating mypy, that's not good either.  

It seems to me that when I run mypy from the minibuffer, mypy is more strict than when you use it.  The only mypy configuration I have is whatever is in the leo-editor git repo after a pull.  If you are using some different version, then we need to get sorted out how a developer can get the same configuration files as you use, and get the same results.

I don't want to be forced to run mypy externally on the whole repo just to check an external file I'm working on so I can work out the right typing annotations. They have been chewing up more than enough effort as it is.

2024-10-28 13:16 UTC, edreamleo commented
@tbpassin You're not responsible for mypy checks. I am. Don't worry about it.

Otoh, my `mypy-leo.cmd` takes only a few seconds. It seems inherently more reliable than checking a single file. I often run pylint from the command line but I never run mypy from the command line.

In short, the present annotations are good enough for me. Let's move on.

2024-10-28 13:49 UTC, tbpassin commented
> You're not responsible for mypy checks. I am. Don't worry about it.

Well, yes, OK.  But we have had some history about this.  When I've forgotten to run mypy and there are type annotation errors, you have complained that I should have run mypy.  This time I sweated blood to get mypy as run by me from the minibuffer to accept the annotations, and you say my solutions were too complicated. Now you say that mypy compliance is for you and for me not to worry about it.

So here's how I plan to proceed in the future unless you have a better suggestion.  I will put in whatever type annotations seem to make sense to me and I won't make them pass mypy as run by me.

The mypy command should still be fixed.  Also, now I'm wondering that if I run mypy from the minibuffer on an external file that is not part of the Leo directory tree, whether it will even be configured the way it should be.

2024-10-28 16:13 UTC, tbpassin commented
> Previously, I had assumed you could produce reasonable mypy annotations. Now, I don't. I don't know why you are having troubles.

I went by the mypy messages I got.  It's not like I'm looking for ways to complicate the annotations.  Since you didn't get the same mypy messages I got, you assume I'm doing annotations wrong, and I assume there is some reason for the discrepancies and it's not that I am incompetent or stupid.  Of course, I've been wrong before...

One of the things I've learned the hard way is that when I write

```
QWidget = QtWidgets.QWidget
widget: QWidget = get_widget('name')
```

on my system, when executed from the minibuffer, mypy will claim there's a type error.  On my system, when executed from the minibuffer, mypy will accept

`widget: QtWidgets.QWidget = get_widget('name')`

Or maybe not even then, depending on how `get_widget()` was annotated  This is perplexing to me because I thought a type system is supposed to be able to trace types through the assignments.

2024-10-28 18:58 UTC, edreamleo commented
@tbpassin You said you weren't looking for complications. That's laudable. Yet somehow you wrote this:
```python
class LayoutCacheWidget(Generic[QW], QtWidgets.QWidget):
```
That's utter nonsense. My guess this annotation sent both you and mypy down a ravine.

The only correct annotation is:
```python
class LayoutCacheWidget(QWidget):
```
Note that `QWidget`, the base class, needs no annotation!

The weird `_: str` annotations were a strong clue that something was seriously amiss.

But let's move on. Here are my recommendations:

- Never run Leo's `mypy` command from the minibuffer.
- Always run mypy using `leo/scripts/mypy_leo.py`
  I use `mypy-leo.cmd`. It contains: `python -m leo.scripts.mypy_leo`
- Start again if annotations get out of control.

HTH.

2024-10-28 19:19 UTC, edreamleo commented
@tbpassin One more recommendation. Study the annotations in Leo's gui files. They all follow roughly the same pattern. None need to go to heroic lengths to annotate any. Yes, there are times when `Any` annotations and `type:ignore` suppressions are necessary and appropriate. I usually avoid `Union` annotations: they are difficult to get right.

2024-10-28 19:20 UTC, edreamleo commented
@tbpassin Please approve this PR. It's time for everyone to start testing it.

2024-10-29 00:02 UTC, tbpassin requested changes
qt_gui.py
------------
### Lines 1524 ff:

```
QSignalSpy = QtTest.QSignalSpy
    assert QSignalSpy
```
QSignalSpy is a new addition that doesn't seem to be used (yet) and has nothing to do with the rest of this PR.  Yet there is an assert.  If there is any possibility that the assert might fail, then this code will quit (I'm not sure if Leo will quit at that point or not). If there is an assert about this import, why not about other Qt imports.  also, what is this import doing in the middle of the module instead of its start?

I recommend removing the assert, and preferably the entire QSignalSpy parts, which should await a separate PR.

### Line 1536
`def find_parent_splitter(self, widget: QWidget) -> Optional[Tuple[QSplitter, Any]]:`

The type of the return should be 

`Optional[Tuple[QSplitter, QWidget]]`

### Line 1542
```
child is the *direct* child of the splitter that contains the widget.
          The child might or might not be the widget itself.
```

I find this terminology confusing. I also don't understand the reason for returning some widget that isn't the one we asked for. The "direct" child might not even be the parent of the widget we asked for. In principle, it could be e.g. the grandparent of our widget.  I don't know how to word it concisely, but the widget in question in the first descendant on the line of descent from the splitter to our widget. "Direct" didn't convey that to me.

qt_layout.py
----------------
### Line 430:
`a layout data structure such as the following:0`

The last character was probably meant to be a second ":"  for RsT literal block syntax.

### Line 478 ff
```
        if is_module_loaded(VR3_MODULE_NAME):
            from leo.plugins.viewrendered3 import controllers
            vr3 = controllers.get(c.hash())
            self.contract_pane(vr3)
```
It's not guaranteed that VR3 will be in a splitter.  When it is created it is made a child of the layout cache.  If a layout doesn't have a slot for it, it won't be in a splitter.  All the current layouts  do have a slot for it, but someone could create another one that doesn't.

I'm not sure if the same is true when the VR instance is created

2024-10-29 09:01 UTC, edreamleo commented
@tbpassin Thanks for your review!

- `assert QSignalSpy`: The code must stay as it is.
  The import and assert are inside `LeoQtGui.enableSignalDebugging`, a *debugging* method.
  The caller is responsible for any problems.
  Anyway, (except during startup) Leo will *never* exit as the result of a crash.

- `def find_parent_splitter(self, widget: QWidget) -> Optional[Tuple[QSplitter, Any]]:`
  The annotation is correct.

  The `LCW.find_parent_splitter` method returns a *child* (the so-called **direct child**) of the found splitter,
  *not* the `widget` arg, which might be a descendant.
  This little trick collapses the complexity of `LCW.resize_pane`!

- `a layout data structure such as the following:0`
  Good catch.

- It's not guaranteed that VR3 will be in a splitter.
  `LCW.contract_pane` does not require that guarantee.

I'll make one more change: The headline of `LCW.resize_pane` was `LCW.resize_widget`.

**Summary**

Thanks for your detailed reading of the code.
Rev 5042a9f changes one headline and one docstring.

2024-10-29 16:43 UTC, tbpassin approved these changes

2024-10-29 16:46 UTC, merged